#ifndef _SMM_CONFIG_H
#define _SMM_CONFIG_H

#define SMM_CONFIG_HSPI_MISO_PIN 12
#define SMM_CONFIG_HSPI_MOSI_PIN 13
#define SMM_CONFIG_HSPI_CLK_PIN 14

#define SMM_CONFIG_MCP3208_HOST_ID HSPI_HOST
#define SMM_CONFIG_MCP3208_CS_PIN 15
#define SMM_CONFIG_MCP3208_CLK_FREQ_HZ 6000000

#define SMM_CONFIG_I2C_NUM_0_SDA_PIN 21
#define SMM_CONFIG_I2C_NUM_0_SCL_PIN 22
#define SMM_CONFIG_I2C_NUM_0_CLK_FREQ_HZ 100000
#define SMM_CONFIG_I2C_NUM_0_SDA_PULLUP_EN GPIO_PULLUP_ENABLE
#define SMM_CONFIG_I2C_NUM_0_SCL_PULLUP_EN GPIO_PULLUP_ENABLE

#define SMM_CONFIG_LCD_I2C_PORT I2C_NUM_0
#define SMM_CONFIG_LCD_ADDRESS 0x27
#define SMM_CONFIG_LCD_COLUMNS 16
#define SMM_CONFIG_LCD_ROWS 2

#define SMM_CONFIG_MENU_COLUMNS SMM_CONFIG_LCD_COLUMNS
#define SMM_CONFIG_MENU_ROWS SMM_CONFIG_LCD_ROWS

#define SMM_CONFIG_BUTTONS_BTN_UP_PIN 32
#define SMM_CONFIG_BUTTONS_BTN_DOWN_PIN 33
#define SMM_CONFIG_BUTTONS_SHORT_PRESS_TIME 150
#define SMM_CONFIG_BUTTONS_LONG_PRESS_TIME 750

#endif
